In [64]:
import torch
import torch.nn as nn
import torch.nn.functional as F


torch.manual_seed(46)

W = torch.randn(2,2, requires_grad=True)
b = torch.randn(2,1, requires_grad=True)

x, y = torch.randn(2,1, requires_grad=True), torch.Tensor([2,1])


z = W.mm(x) + b
print(z)

a = F.sigmoid(z)
print(a)

loss = F.binary_cross_entropy(a,y)
print("Loss:", loss)

tensor([[-0.7018],
        [ 0.9822]], grad_fn=<AddBackward0>)
tensor([[0.3314],
        [0.7275]], grad_fn=<SigmoidBackward>)
Loss: tensor(1.0621, grad_fn=<BinaryCrossEntropyBackward>)


c:\users\andreas stöffelbauer\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:20: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 1])) is deprecated. Please ensure they have the same size.


In [65]:
loss.backward()

In [66]:
alpha = .01

W = W - alpha*W.grad
print(W)

b = b - alpha*b.grad
print(b)

z = W.mm(x) + b
a = F.sigmoid(z)
loss = F.binary_cross_entropy(a,y)
print("Loss:", loss)

tensor([[-0.1276,  0.5147],
        [ 1.2062,  0.3087]], grad_fn=<SubBackward0>)
tensor([[0.4726],
        [1.0136]], grad_fn=<SubBackward0>)
Loss: tensor(1.0227, grad_fn=<BinaryCrossEntropyBackward>)


c:\users\andreas stöffelbauer\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 1])) is deprecated. Please ensure they have the same size.
  # This is added back by InteractiveShellApp.init_path()


In [60]:
W.size()
W.view(-1,1)


tensor([[-0.1276,  0.5147],
        [ 1.2062,  0.3087]], grad_fn=<SubBackward0>)

In [266]:


class Net(nn.Module):
    
    def __init__(self, d_in, d_hidden1, d_hidden2, d_out):
        super().__init__()
        #self.n_batch = n_batch
        self.d_in = d_in
        self.d_hidden1 = d_hidden1
        self.d_hidden2 = d_hidden2
        self.d_out = d_out
        
        self.fc1 = nn.Linear(self.d_in, self.d_hidden1)
        self.fc2 = nn.Linear(self.d_hidden1, self.d_hidden2)
        self.fc3 = nn.Linear(self.d_hidden2, self.d_out)
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.softmax(self.fc3(x))
        return x
        
     
        

In [294]:
torch.manual_seed(9877)

net = Net(784,128,64,10)

x = torch.randn(2,784)
y = torch.randn(1,10)

print(y.shape)
out = net(x)
print(out)


F.mse_loss(out,y).sum()

torch.Size([1, 10])
tensor([[0.0754, 0.1276, 0.0830, 0.0951, 0.0940, 0.1104, 0.1027, 0.0947, 0.1116,
         0.1055],
        [0.0916, 0.1009, 0.0919, 0.0905, 0.0877, 0.1161, 0.1043, 0.1027, 0.1188,
         0.0956]], grad_fn=<SoftmaxBackward>)


c:\users\andreas stöffelbauer\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:18: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
c:\users\andreas stöffelbauer\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Using a target size (torch.Size([1, 10])) that is different to the input size (torch.Size([2, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  del sys.path[0]


tensor(1.1034, grad_fn=<SumBackward0>)

In [242]:
### Run this cell

from torchvision import datasets, transforms

# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Normalize((0.5,), (0.5,)),
                              ])
# Download and load the training data
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

100.1%

Extracting C:\Users\Andreas Stöffelbauer/.pytorch/MNIST_data/MNIST\raw\train-images-idx3-ubyte.gz to C:\Users\Andreas Stöffelbauer/.pytorch/MNIST_data/MNIST\raw


113.5%

Extracting C:\Users\Andreas Stöffelbauer/.pytorch/MNIST_data/MNIST\raw\train-labels-idx1-ubyte.gz to C:\Users\Andreas Stöffelbauer/.pytorch/MNIST_data/MNIST\raw


100.4%

Extracting C:\Users\Andreas Stöffelbauer/.pytorch/MNIST_data/MNIST\raw\t10k-images-idx3-ubyte.gz to C:\Users\Andreas Stöffelbauer/.pytorch/MNIST_data/MNIST\raw


180.4%

Extracting C:\Users\Andreas Stöffelbauer/.pytorch/MNIST_data/MNIST\raw\t10k-labels-idx1-ubyte.gz to C:\Users\Andreas Stöffelbauer/.pytorch/MNIST_data/MNIST\raw
Processing...
Done!


In [258]:
dataiter = iter(trainloader)
images, labels = dataiter.next()
print(type(images))
print(images.shape)
print(labels.shape)

<class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64])


tensor([9, 9, 9, 1, 1, 2, 8, 1, 9, 9, 1, 6, 0, 3, 9, 6, 6, 1, 0, 0, 3, 5, 7, 4,
        4, 1, 2, 9, 1, 0, 0, 6, 1, 7, 7, 5, 7, 3, 1, 6, 2, 0, 6, 8, 8, 4, 5, 8,
        5, 4, 3, 4, 7, 6, 3, 8, 3, 6, 3, 8, 7, 1, 1, 0])